// Package pipeline is the shared generate pipeline used by both the `generate`
// command and the `audit` loop.
package pipeline

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/kwistof/cnpgen/internal/collect"
	"github.com/kwistof/cnpgen/internal/generate"
	"github.com/kwistof/cnpgen/internal/hubble"
	"github.com/kwistof/cnpgen/internal/model"
	"github.com/kwistof/cnpgen/internal/patterns"
	"github.com/kwistof/cnpgen/internal/settings"
	"github.com/kwistof/cnpgen/internal/ui"
)

// GeneratePolicies turns raw flows into policies.
//
// label plus namespace together select which pods are "ours" (a
// CiliumNetworkPolicy only ever matches pods in its own namespace, so the two
// must agree). namespace is also where every policy is written/deployed (the
// CNP object's own metadata.namespace). tempDNS injects the temporary
// kube-dns visibility rule; prune then removes it from policies that ended up
// with no toFQDNs. seed, if not nil, is merged into every generated policy as
// an unconditional floor (see generate.Seed).
func GeneratePolicies(flows []*hubble.Flow, label, namespace string, index *model.ResolveIndex,
	cfg settings.Settings, accept, tempDNS, prune bool, seed *generate.Seed) []*generate.Policy {

	graph := collect.ExtractConnections(flows, label, namespace)

	// Sort endpoints by (App, Namespace) for deterministic output.
	eps := make([]model.Endpoint, 0, graph.Len())
	for ep := range graph.Buckets() {
		eps = append(eps, ep)
	}
	sort.Slice(eps, func(i, j int) bool {
		if eps[i].App != eps[j].App {
			return eps[i].App < eps[j].App
		}
		return eps[i].Namespace < eps[j].Namespace
	})

	var out []*generate.Policy
	for _, ep := range eps {
		bucket := graph.Buckets()[ep]
		p := generate.BuildPolicy(ep.App, ep.Namespace, bucket, index, cfg, accept, tempDNS, seed)
		if p == nil {
			continue
		}
		if prune {
			p.PruneTempDNS()
		}
		p.Namespace = namespace
		// The policy doc's metadata.namespace must reflect the deploy namespace.
		p.SetDeployNamespace(namespace)
		out = append(out, p)
	}
	return out
}

// WritePolicies writes each policy to outdir/<file>, and removes any other
// .yaml/.yml file already there (outdir is treated as owned by the current
// run). Returns the file paths written.
func WritePolicies(policies []*generate.Policy, outdir string) ([]string, error) {
	if err := os.MkdirAll(outdir, 0o755); err != nil {
		return nil, err
	}
	var paths []string
	keep := map[string]struct{}{}
	for _, p := range policies {
		name := p.FileName()
		path := filepath.Join(outdir, name)
		if err := os.WriteFile(path, []byte(p.YAML()), 0o644); err != nil {
			return nil, err
		}
		paths = append(paths, path)
		keep[name] = struct{}{}
	}
	entries, err := os.ReadDir(outdir)
	if err != nil {
		return nil, err
	}
	for _, e := range entries {
		name := e.Name()
		if strings.HasSuffix(name, ".yaml") || strings.HasSuffix(name, ".yml") {
			if _, ok := keep[name]; !ok {
				_ = os.Remove(filepath.Join(outdir, name))
			}
		}
	}
	return paths, nil
}

// DescribeTarget returns a one-line description of which pods a command targets.
func DescribeTarget(label, namespace string) string {
	return "'" + label + "' in " + namespace
}

// PrintNotes prints each policy's per-app decision notes.
func PrintNotes(policies []*generate.Policy) {
	for _, p := range policies {
		ns := p.ObservedNS
		if ns == "" {
			ns = p.Namespace
		}
		for _, note := range p.Notes {
			fmt.Printf("  %s %s\n", ui.Dim(fmt.Sprintf("[%s/%s]", ns, p.Name)), note)
		}
	}
}

// PrintNewNotes prints each policy's per-app decision notes, skipping any
// note whose exact text was already printed for that policy in an earlier
// call (tracked via seen, keyed by "<file name>\x00<note text>": the caller
// owns and reuses the same map across rounds). A round that resolves one new
// domain doesn't need to re-explain wildcard suggestions or unresolved IPs
// that haven't changed since the last round they were shown.
func PrintNewNotes(policies []*generate.Policy, seen map[string]struct{}) {
	for _, p := range policies {
		ns := p.ObservedNS
		if ns == "" {
			ns = p.Namespace
		}
		for _, note := range p.Notes {
			key := p.FileName() + "\x00" + note
			if _, ok := seen[key]; ok {
				continue
			}
			seen[key] = struct{}{}
			fmt.Printf("  %s %s\n", ui.Dim(fmt.Sprintf("[%s/%s]", ns, p.Name)), note)
		}
	}
}

// Signature returns a deterministic fingerprint of a policy set's content
// (file name + rendered YAML + notes, sorted by file name). Two rounds that
// produce the same signature generated byte-identical policies for the same
// reasons, so the audit loop can skip reprinting notes/apply results that
// would just repeat what was already shown.
func Signature(policies []*generate.Policy) string {
	names := make([]string, 0, len(policies))
	byName := make(map[string]*generate.Policy, len(policies))
	for _, p := range policies {
		name := p.FileName()
		names = append(names, name)
		byName[name] = p
	}
	sort.Strings(names)
	var b strings.Builder
	for _, name := range names {
		p := byName[name]
		b.WriteString(name)
		b.WriteByte('\n')
		b.WriteString(p.YAML())
		b.WriteByte('\n')
		for _, note := range p.Notes {
			b.WriteString(note)
			b.WriteByte('\n')
		}
	}
	return b.String()
}

// CollectSuggestions aggregates pattern suggestions across all policies.
func CollectSuggestions(policies []*generate.Policy) []patterns.Suggestion {
	seen := map[string]patterns.Suggestion{}
	var order []string
	for _, p := range policies {
		for _, s := range p.Suggestions {
			if _, ok := seen[s.Suffix]; !ok {
				seen[s.Suffix] = s
				order = append(order, s.Suffix)
			}
		}
	}
	out := make([]patterns.Suggestion, 0, len(order))
	for _, suffix := range order {
		out = append(out, seen[suffix])
	}
	return out
}

// CollectUnresolved aggregates unresolved external CIDRs across all policies.
func CollectUnresolved(policies []*generate.Policy) []generate.Unresolved {
	seen := map[generate.Unresolved]struct{}{}
	for _, p := range policies {
		for _, u := range p.Unresolved {
			seen[u] = struct{}{}
		}
	}
	out := make([]generate.Unresolved, 0, len(seen))
	for u := range seen {
		out = append(out, u)
	}
	sort.Slice(out, func(i, j int) bool {
		if out[i].CIDR != out[j].CIDR {
			return out[i].CIDR < out[j].CIDR
		}
		if out[i].Port != out[j].Port {
			return out[i].Port < out[j].Port
		}
		return out[i].Proto < out[j].Proto
	})
	return out
}
